// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:resident/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PhoneNumberAdapter());
    registerAdapter(PropertyAdapter());
    registerAdapter(UnitAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PhoneNumberAdapter());
    registerAdapter(PropertyAdapter());
    registerAdapter(UnitAdapter());
    registerAdapter(UserAdapter());
  }
}
